// <auto-generated />
namespace VentaVehiculos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migracionInicial2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracionInicial2));
        
        string IMigrationMetadata.Id
        {
            get { return "202108240544453_migracionInicial2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
